### DISCUSSION TITLE
Op composition (Base Op)

### DISCUSSION THREAD

**Discussion by LiorRemitly** [opctl/opctl#1143] [Q&A] [answered]
Hi all,
I'm working with multiple Ops that all have some shared setup (e.g. mounting some fixed number of directories/files, running yarn install, etc.).
Then I want to use this Op as a base Op for other cases (e.g. running unit tests).
Couldn't find a proper way to do it in the documentation. Seems like I can ref another Op, but then I can't give it another cmd.
Is it possible? If so, I'd love an example.
I can provide more context if needed.

Thank you!

**Comment by chrisdostert** [comment, marked as answer]
Hi @LiorRemitly, you can use inputs to parameterize the op. One of the parameters could be a command or part of a command e.g.

```
name: parameterized-cmd
inputs:
  src:
    description: source directory to mount
    dir:
      default: .
  cmd:
    description: command to run
    array:
      default:
        - yarn
        - -v
run:
  container:
    image:
      ref: node:alpine
    cmd: $(cmd)
    dirs:
      /src: $(src)
    workDir: /src
```
