### ISSUE TITLE
CLI no longer logs errors occurring in parallel calls

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#1032]
## 🐛 Bug Report

Since version 0.1.48 (latest at time of filing), errors occurring in child calls of parallel blocks are not being logged in the CLI.

## To Reproduce

1. create an op with a parallel block that has children that will error
    ``` yaml
    name: repro
    run: 
      parallel:
        - container:
            image:
              ref: alpine
            cmd:
              - sh
              - -ce
              - exit 1    
        - container:
            image:
              ref: alpine
            cmd:
              - sh
              - -ce
              - exit 1
    ```
1. run the op

## Expected behavior

the following is logged (ignoring prefixes)
```shell
[6d2b7612 .] started op
[99b0e8ae .] started docker.io/library/alpine
[4e14d90a .] started docker.io/library/alpine
[4e14d90a] latest: Pulling from library/alpine
[99b0e8ae] latest: Pulling from library/alpine
[4e14d90a] Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
[4e14d90a] Status: Image is up to date for alpine:latest
[99b0e8ae] Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
[99b0e8ae] Status: Image is up to date for alpine:latest
[4e14d90a .] docker.io/library/alpine crashed: nonzero container exit code: 1
[99b0e8ae .] docker.io/library/alpine killed
[6d2b7612 .] op failed: child call failed
```

## Actual Behavior

the following is logged
```shell
[49834a0b .] started op
[a194d25b .] started docker.io/library/alpine
[feaee4ec .] started docker.io/library/alpine
[feaee4ec] latest: Pulling from library/alpine
[feaee4ec] Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
[feaee4ec] Status: Image is up to date for alpine:latest
[a194d25b] latest: Pulling from library/alpine
[a194d25b] Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
[a194d25b] Status: Image is up to date for alpine:latest
[feaee4ec .] docker.io/library/alpine crashed
[a194d25b .] docker.io/library/alpine killed
[49834a0b .] op failed: child call failed
```
