### ISSUE TITLE
Escaped references are not escaped if an unescaped '$' exists prior in the string

### ISSUE THREAD

**Issue by squatched** [opctl/opctl#1063]
## 🐛 Bug Report

When one adds an escaped reference to a string (`\$(...)`), the literal `$(...)` should be passed to the underlying construct. But if that string contains an unescaped `$` before the escaped reference that is not itself part of a reference, then the subsequent escape is ignored and an error is produced that states "unable to interpret '...' as reference: '...' not in scope".

Before reporting an issue please remember:
-  One issue, one bug: Please report a single bug per issue.

I would expect a string like `$ \$(...)` to evaluate to the literal string `$ $(...)`.

## To Reproduce

(Write your steps here:)

1. Create an op.yml containing:
```yml
name: test-escaped-ref-issue
run:
  container:
    image: { ref: 'alpine' }
    cmd:
      - sh
      - -ce
      - |
        echo "\$(echo hello)"

        FAILURE="this shouldn't fail"
        echo "${FAILURE}: \$(echo hello again)"

```
1. Run the op.

## Expected behavior

I expected output like the following:
```
hello
this shouldn't fail: hello again
```

## Actual Behavior

Instead, an error is produced stating that the string couldn't be interpreted because `echo hello again` is an out of scope reference:
```
op failed: unable to interpret echo "\$(echo hello)"

FAILURE="this shouldn't fail"
echo "${FAILURE}: \$(echo hello again)"
 to string: unable to interpret 'echo hello again' as reference: 'echo hello again' not in scope
```
