### ISSUE TITLE
Make `Array Parameter [object]` Compatible With A `Container Call [object].cmd`

### ISSUE THREAD

**Issue by squatched** [opctl/opctl#1064]
## 🚀 Feature

`Container Call`'s `cmd` is [documented](https://opctl.io/docs/reference/opspec/op-directory/op/call/container#cmd) as "An array of string initializers..." and if I create an input that is an `Array Parameter` of strings, I expect that they would work together but currently that yields a type error: `Expected: array, given: string`.

Here's an example op.
```yaml
name: test-array-input-as-cmd
inputs:
  input-array:
    array:
      default: [ echo, testing ]
      constraints:
        items:
          type: string
run:
  container:
    image: { ref: 'alpine' }
    cmd: $(input-array)
```

## Motivation

When I create an `Array Parameter`, I would like to be able to pass it directly to `Container Call`'s `cmd` property. This would allow me to parameterize my build environment setup in one op, then reuse it throughout all my ops for a consistent environment. (I'm currently working around this by passing the input as a string type and then embedding it into `cmd: [sh, -ce, $(input)]` which works, but the call syntax is inconsistent with expectations and can lead to confusion for future maintainers.)

## Pitch

My naive proposal is to support an `Array Parameter` to be coerced into an array of string initializers. But ultimately, I just want an `Array Parameter` to work where an "array of *" is allowed. Whether or not constraints must be specified or array item coercion determines the viability of the array coercion, I'm not sure and am not close enough with opctl's implementation to make the right call.
