### ISSUE TITLE
`isSecret` Parameters Are Displayed In ClearText On Stdout

### ISSUE THREAD

**Issue by squatched** [opctl/opctl#1066]
## 🐛 Bug Report

When declaring a parameter as `isSecret`, and then using it as part of `container.cmd`, the secret is leaked into stdout as part of the output.

## To Reproduce

Here's an op to demonstrate.
```yaml
name: test-secrets

inputs:
  creds:
    object:
      isSecret: true
      constraints:
        properties:
          accessToken: { minLength: 1, type: string, writeOnly: true }
          username: { minLength: 1, type: string }
        required: [ accessToken, username ]
      description: Configuration required to interact with GitHub.
  password:
    string:
      isSecret: true
      constraints: { minLength: 1 }
      description: Another secret password.

run:
  container:
    image: { ref: alpine }
    # Added space at the start of the command to disable shell history for the command.
    # 'true' command is just to simulate execution of something.
    cmd: [sh, -ce, " CREDENTIALS_USER=\"$(creds.username)\" CREDENTIALS_TOKEN=\"$(creds.accessToken)\" ACCESS_PASSWORD=\"$(password)\" true"]
```

Here's the completed output from running this op (with `creds` and `password` defined as something):
```
$ opctl run test-secrets
[8494116e ./.opspec/test-secrets] started op
[8a97a93b ./.opspec/test-secrets] started docker.io/library/alpine
[8a97a93b] latest: Pulling from library/alpine
[8a97a93b] Digest: sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11
[8a97a93b] Status: Image is up to date for alpine:latest
[8a97a93b ./.opspec/test-secrets] docker.io/library/alpine exited
[8494116e ./.opspec/test-secrets] op succeeded
┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
◎ ☑ ./.opspec/test-secrets 3.846550859s
└─◉ ☑ 8a97a93b docker.io/library/alpine 3.842746067s sh -ce  CREDENTIALS_USER="secret-squirrel" CREDENTIALS_TOKEN="accessToken for my winter stash" ACCESS_PASSWORD="int'l sneaky service password" true
```

## Expected behavior

I would expect any input that is marked as `isSecret` to, at the very least, not be placed into stdout when it's used directly in a command. I would expect any place that those are referenced directly to obfuscate the contents with `*`s or something.

## Actual Behavior

The secrets are logged in plain text.
