### ISSUE TITLE
New Feature Allowing Array As `run.container.cmd` Fails

### ISSUE THREAD

**Issue by squatched** [opctl/opctl#1068]
## 🐛 Bug Report

When testing the proposed fix for #1064 , I discovered that I consistently get a very long hang and then a type failure.

## To Reproduce

1. Create an op like the following:
```yaml
name: test-array-input-issue
inputs:
  input-array:
    array:
      default: [ echo, testing ]
run:
  container:
    image: { ref: 'alpine' }
    cmd: $(input-array)
```
2. Execute it: `opctl run test-array-input-issue`

## Expected behavior

I expected the command `echo testing` to be run within the container.

## Actual Behavior

A hang for a minute and a half and then error:

```
$ opctl --version
0.1.52
$ time opctl run test-array-input-issue

-
  Error(s):
    - run.container.cmd: Invalid type. Expected: array, given: string
-


real    1m29.443s
user    0m0.055s
sys     0m0.080s
```
