### ISSUE TITLE
Opctl DNS Resolution Breaks `systemd-resolved` DNS Resolution

### ISSUE THREAD

**Issue by squatched** [opctl/opctl#1151]
## 🐛 Bug Report

When using a Linux system that uses systemd-resolved to manage name resolution, the moment that opctl inserts itself into `/etc/resolv.conf`, all name resolution for anything other than an opctl container name fails. `opctl node kill` then brings it all back.

## To Reproduce

1. On a Linux system that uses `systemd-resolved` for DNS resolution (e.g. Ubuntu since 20.04), create the following op:
```yml
name: test-dns
description: Container to test opctl's DNS resolution.
run:
  container:
    name: opctl-dns-test
    cmd:
        - sh
        - -ce
        - |
            printf "Container's network name is 'opctl-dns-test'.\n"
            printf "Hanging indefinitely. Kill with Ctrl+C\n"
            tail -f /dev/null
    image: { ref: alpine }

```

2. Confirm that DNS of an external domain works.
```
$ dig +short github.com
140.82.114.3
$ 
```
4. Run the op (`opctl run test-dns`)
5. In another terminal, observe that DNS lookup for an external domain now fails but the opctl DNS succeeds.
```
$ dig +short github.com
$ dig +short opctl-dns-test
172.20.0.2
$ 
```
6. Kill the running op and the opctl node.
7. Observe that, once again, external DNS lookups succeed.
```
$ opctl node kill
$ dig +short github.com
140.82.112.4
$ 
```

## Expected behavior

opctl DNS lookup shoulf fail for an external domain and then fallback to previously configured DNS.

## Actual Behavior

If opctl DNS service does not know the domain, the entire DNS lookup fails.
