### ISSUE TITLE
Container w/ invalid image hangs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#222]
```yaml
parallel:
  - op: # something that immediately fails
  - serial: # something that eventually succeeds
```
