### ISSUE TITLE
Passing sub op inputs intermittently broken

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#238]
given:
```yaml
name: minimal-reproducible-example
input:
  in1:
    dir: {}
run:
  serial:
    - op: {pkg: {ref: sibling1}, inputs: {in1}, outputs: {out1}}
    - op: {pkg: {ref: sibling2}, inputs: {out1}}
```

expected:
1) run `minimal-reproducible-example`
2) sibling2 receives expected out1

actual:
1) run `minimal-reproducible-example`
2) sometimes sibling2 does not receive expected out1
