### ISSUE TITLE
"too many open files" error encountered when run via cron

### ISSUE THREAD

**Issue by poppuyo** [opctl/opctl#289]
Environment:
Ubuntu 17.04 
$ docker -v
Docker version 17.06.0-ce, build 02c1d87
$ opctl -v
0.1.20

Note, this is running in cron:

Command
```
/usr/bin/flock -n /tmp/email.lockfile ~/testsrc/email-handler/run-from-cron.sh >> ~/logs/email-handler.log
```

run-from-cron.sh:
```sh
#!/bin/sh
cd "${0%/*}"
/usr/local/bin/opctl --nc run init
```

init.op:
```yaml
name: init
description: inits the email-handler prereqs
# inputs:
#   srcDir:
#     dir:
#       default: .
#       description: directory containing the app
# outputs:
#   srcDir:
#     dir:
#       description: directory containing the app
run:
  container:
    cmd: [ npm, install ]
    #dirs:
    #  /src: srcDir
    image: { ref: 'node:8-alpine' }
    workDir: /src

```

Error:
```
OpErred Id='2567a7add6234c7449f61960b4bfb474' PkgRef='init' Timestamp='2017-08-08T17:28:01Z' Msg='
-
  Error(s):
    - open /home/jason/testsrc/email-handler/.opspec/init/op.yml: too many open files
-'

OpEnded Id='2567a7add6234c7449f61960b4bfb474' PkgRef='init' Outcome='FAILED' Timestamp='2017-08-08T17:28:01Z'
```
