### ISSUE TITLE
UI: WYSIWYG operation visualizer

### ISSUE THREAD

**Issue by psamaan** [opctl/opctl#452]
As an opctl user
I want to see a visual representation of my op
So that I can more easily understand logical flow and mapping of inputs to outputs

Example:
```
name: test
description: runs all tests
inputs:
  srcDir:
    dir:
      default: .
      description: directory containing the projects source code
outputs:
  srcDir:
    dir:
      description: directory containing the projects source code
  coverprofile:
    file:
      description: aggregate coverprofile
run:
  serial:
    - op:
        pkg: { ref: clean }
        inputs: { srcDir }
        outputs: { srcDir }
    - parallel:
        - op:
            ref: github.com/opspec-pkgs/golang.fmt#1.1.0
            inputs: { srcDir }
            outputs: { srcDir }
        - op:
            ref: test/unit
            inputs: { srcDir }
            outputs: { srcDir, coverprofile }
        - op:
            ref: webapp/test
            inputs: { srcDir: $(srcDir/webapp) }
```

would render something like [this](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBpbnB1dHM-aW5wdXRzXS0tPnxzcmNEaXJ8Y2xlYW5cbiAgICBzdWJncmFwaCBydW5cbiAgICBjbGVhbi0tPnxzcmNEaXJ8bWlkPmlucHV0c11cbiAgICBzdWJncmFwaCBwYXJhbGxlbFxuICAgIG1pZC0tPnxzcmNEaXJ8Z2l0aHViLmNvbS9vcHNwZWMtcGtncy9nb2xhbmcuZm10IzEuMS4wXG4gICAgbWlkLS0-fHNyY0Rpcnx0ZXN0L3VuaXRcbiAgICBtaWQtLT58c3JjRGlyL3dlYmFwcHx3ZWJhcHAvdGVzdFxuICAgIGVuZFxuICAgIGVuZFxuICAgIGdpdGh1Yi5jb20vb3BzcGVjLXBrZ3MvZ29sYW5nLmZtdCMxLjEuMC0tPnxzcmNEaXJ8b3V0cHV0cz5vdXRwdXRzXVxuICAgIHRlc3QvdW5pdC0tPnxzcmNEaXJ8b3V0cHV0cz5vdXRwdXRzXVxuICAgIHRlc3QvdW5pdC0tPnxjb3ZlcnByb2ZpbGV8b3V0cHV0cz5vdXRwdXRzXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)
