### ISSUE TITLE
JSON schema input/output

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#491]
## Examples

for the [github.com/opspec-pkgs/azure.cosmosdb.create package](https://github.com/opspec-pkgs/azure.cosmosdb.create) the below demonstrates before/after

### Before
```yaml
inputs:
  subscriptionId:
    string:
      constraints: { minLength: 1 }
      description: id of azure subscription
  loginId:
    string:
      constraints: { minLength: 1 }
      description: id of user, service principal, or app to login with
  loginSecret:
    string:
      constraints: { minLength: 1 }
      description: secret of user, service principal, or app to login with
      isSecret: true
  name:
    string:
      constraints: { minLength: 1 }
      description: name of provisioned db
  resourceGroup:
    string:
      constraints: { minLength: 1 }
      description: name of azure resource group
  locations:
    string:
      constraints: { minLength: 1 }
      description: space separated locations of provisioned db in 'regionName=failoverPriority' format
      default: West US=0
  defaultConsistencyLevel:
    string:
      constraints: { enum: [BoundedStaleness, ConsistentPrefix, Eventual, Session, Strong] }
      description: default consistency level of the provisioned db
      default: Eventual
  kind:
    string:
      constraints: { enum: [GlobalDocumentDB, MongoDB, Parse] }
      description: type of the provisioned db
      default: GlobalDocumentDB
  loginTenantId:
    string:
      constraints: { minLength: 1 }
      description: tenant id of user, service principal, or app to login with
      default: " "
  loginType:
    string:
      constraints: { enum: [user, sp]}
      description: type of login; 'user' (default) or 'sp' for service principal
      default: user
  maxInterval:
    number:
      constraints: { format: integer, minimum: 1, maximum: 100 }
      description: tolerated record staleness (in seconds) for provisioned db
      default: 5
  maxStalenessPrefix:
    number:
      constraints: { format: integer, minimum: 1, maximum: 2147483647 }
      description: tolerated number of stale requests for provisioned db
      default: 100
  ipRangeFilter:
    string:
      constraints: { minLength: 1 }
      description: comma separated list of IPs in CIDR format to allow through firewall of provisioned db
      default: 0.0.0.0/0
```

### After
```yaml
input:
  properties:
    login:
      properties:
        type:
          enum: [ user, sp]
          description: type of login; 'user' (default) or 'sp' for service principal
          default: user
        id:
          minLength: 1
          description: id of user, service principal, or app to login with
        secret:
          minLength: 1
          description: secret of user, service principal, or app to login with
          writeOnly: true
        tenantId:
          minLength: 1
          description: tenant id of user, service principal, or app to login with
    subscriptionId:
      minLength: 1
      description: id of azure subscription
    name:
      minLength: 1
      description: name of provisioned db
    resourceGroup:
      minLength: 1
      description: name of azure resource group
    locations:
      minLength: 1
      description: space separated locations of provisioned db in 'regionName=failoverPriority' format
      default: West US=0
    defaultConsistencyLevel:
      enum: [BoundedStaleness, ConsistentPrefix, Eventual, Session, Strong]
      description: default consistency level of the provisioned db
      default: Eventual
    kind:
      enum: [GlobalDocumentDB, MongoDB, Parse]
      description: type of the provisioned db
      default: GlobalDocumentDB
    maxInterval:
      format: integer
      minimum: 1
      maximum: 100
      description: tolerated record staleness (in seconds) for provisioned db
      default: 5
    maxStalenessPrefix:
      format: integer
      minimum: 1
      maximum: 2147483647
      description: tolerated number of stale requests for provisioned db
      default: 100
    ipRangeFilter:
      minLength: 1
      description: comma separated list of IPs in CIDR format to allow through firewall of provisioned db
      default: 0.0.0.0/0
```
