### ISSUE TITLE
Declarative concurrency

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#492]
### Background
currently concurrency is imperative i.e. one must declare `serial` or `parallel` call(s). This could be made declarative via introducing a call dependency mechanism. 

#### Build 
before:
```yaml
name: build
description: runs ops necessary to go from src to vetted artifact(s)
inputs:
  gitBranch:
    string:
      constraints: { minLength: 1 }
      description: git branch coverage should be associated with
      default: master
  srcDir:
    dir:
      default: .
      description: directory containing the projects source code
outputs:
  srcDir:
    dir:
      description: directory containing the projects source code
run:
  serial:
    - op:
        pkg: { ref: test }
        inputs: { srcDir }
        outputs: { srcDir, coverprofile }
    - op:
        pkg: { ref: github.com/opspec-pkgs/git.resolve-commit#1.0.0 }
        inputs: { dotGitDir: $(srcDir.git) }
        outputs: { gitCommit: commit }
    - op:
        pkg: { ref: github.com/opspec-pkgs/codecov.upload#1.1.0 }
        inputs: { gitBranch, gitCommit, token: 5f64e6aa-5117-410b-aceb-3188c58e4a18, report: coverprofile }
```

after: 
```yaml
name: build
description: runs ops necessary to go from src to vetted artifact(s)
inputs:
  gitBranch:
    string:
      constraints: { minLength: 1 }
      description: git branch coverage should be associated with
      default: master
  srcDir:
    dir:
      default: .
      description: directory containing the projects source code
run:
  test:
    op: test
    inputs: { srcDir: $(inputs.srcDir) }
  getCommitSha:
    startOn:
      anyOf:
        - $(test.state.SUCCESSFUL)
    op: github.com/opspec-pkgs/git.resolve-commit#1.0.0
    inputs: { dotGitDir: $(inputs.srcDir/.git) }
  uploadCoverage:
    startOn:
      anyOf:
        - $(getCommitSha.state.SUCCESSFUL)
    op: github.com/opspec-pkgs/codecov.upload#1.1.0
    inputs:
      gitBranch: $(inputs.gitBranch)
      gitCommit: $(getCommitSha.outputs.commit)
      token: 5f64e6aa-5117-410b-aceb-3188c58e4a18
      report: $(test.outputs.coverprofile)
outputs:
  srcDir:
    dir:
      value: $(calls.runTests.outputs.srcDir)
      description: directory containing the projects source code
```

#### Acceptance test
before: not possible

after: 
```yaml
name: test-acceptance
run:
  test:
    startOn:
      allOf:
        $(sut1.STARTED)
        $(sut2.STARTED)
    op: test-harness
  sut1:
    killOn:
      anyOf:
        $(test.COMPLETED)
    container: sut1
    name: sut1
  sut2:
    killOn:
      anyOf:
        $(test.COMPLETED)
    container: sut2
    name: sut2
```
