### ISSUE TITLE
Spec to provide interface to enable auto-scaling

### ISSUE THREAD

**Issue by psamaan** [opctl/opctl#493]
## User Story:
**As** a user of the spec
**I want** to reference an op with a specific interface as an "auto-scaler" for any op run
**So** I can scale my ops based on any metric

## Example:

```
run:
  op:
	image: { ref: my-main-op }
	# scale is a pkg adhering to a conventional interface
	scale:
	  pkg: { ref: my-auto-scaler}
          inputs: { metric, threshold } # scaling parameters
          outputs: { increment-by, cooldown } #  how much to increment/decrement count of my-main-op run by and cooldown time after a scaling action is taken before another autoscaler call
          frequency: 30 # how frequently to call scaling op in seconds
```
