### ISSUE TITLE
Container call inputs/outputs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#494]
### User Story
As an opspec implementor
I want explicit inputs & outputs from container calls
In order to unambiguously determine their inputs/outputs

### Example
```yaml
inputs:
  input1:
    file: {}
  input2:
    socket: {}
outputs:
  output1:
    dir: {}
  output2:
    socket: {}
run:
  container:
    inputs:
      image: { ref: alpine }
      fs:
        /rootDir:
          mode: 600
          /childDir1:
            /file1.txt:
              data: i'm a text file
              mode: 600
            /file1:
              data: $(input1)
          /childDir2:
            /file2.sh:
              data: |
                #!/usr/bin/env sh
                echo "i'm an executable shell script"
              mode: 777
      sockets:
        host1: $(input2)
    outputs:
      output1: $(fs./rootDir)
      output2: $(sockets.'/var/run/docker.sock')
```
