### ISSUE TITLE
Container fs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#495]
### User Story
As an pkg author
I want to specify the entire fs of a container being called, including file/dir perms/attributes
In order to avoid changing them imperatively inside the container

### Example
```yaml
  container:
    image: { ref: alpine }
    fs:
      /rootDir:
        /childDir1:
          /file1.txt:
            data: i'm a text file
            mode: 600
            uid: 1000
            gid:
        /childDir2:
          /file2.sh:
            data: |
              #!/usr/bin/env sh
              echo "i'm an executable shell script"
            mode: 777
```

### Reference
- https://github.com/moby/tool/blob/master/docs/yaml.md#files
- https://coreos.com/os/docs/latest/clc-examples.html#files
