### ISSUE TITLE
Support in scope dir as container image

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#498]
## User Story
As an op designer
I want to dereference a dir which is a valid OCI bundle as my containers image
In order to run my container w/out depending on a registry or docker engine socket

## Example
```yml
container:
  image:
    src: # [oci image layout] dir
```
