### ISSUE TITLE
Dir Initializer Syntax

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#500]
Example 1
```yaml
op:
  ref: xyz
  inputs: 
    # where file1 is in scope
      /base:
        /childFile: 
          data: $(file1)
```

this would results in pkg xyz being passed someDir w/ value:
```
/
  |-- base 
    |-- childFile # equal to file1
```

Example 2
see https://github.com/opctl/opctl/issues/495
