### ISSUE TITLE
Allow path expansion in sub op call outputs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#501]
Examples:
```yaml
outputs:
  dstFile:
    file: {}
run:
  op: 
    pkg: { ref: xyz }
    outputs: { dstFile: $(zyxOutputDir)/theirFile.txt }
```

```yaml
outputs:
  dstDir:
    dir: {}
run:
  op: 
    pkg: { ref: xyz }
    outputs: { $(dstDir/subDir): zyxOutputDir}
```
