### ISSUE TITLE
Add schedule support

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#504]
```yaml
# .. snipped
run:
  # cron-format http://www.nncron.ru/help/EN/working/cron-format.htm
  schedule: */1 * * * *
  op:
    pkg: { ref: xyz }
```

ref:
[k8s cron-jobs](https://kubernetes.io/docs/concepts/jobs/cron-jobs/)
