### ISSUE TITLE
Suggestion: isParallel should apply to all ops that are running together (not just the N-1 after the first)

### ISSUE THREAD

**Issue by poppuyo** [opctl/opctl#525]
Current Behavior Example:

```
subOps:
- url: init
- url: buildProjA
- url: buildProjB
  isParallel: true
- url: buildProjC
  isParallel: true
- url: debug-node
```

The above means that buildProj{A,B,C} will run together. I believe this could be confusing and propose a different format:

```
subOps:
- url: init
- url: buildProjA
  isParallel: true
- url: buildProjB
  isParallel: true
- url: buildProjC
  isParallel: true
- url: debug-node
```

The behavior of the proposed format would be more readable (subjectively speaking here, others should feel free to weigh in), as I would understand that buildProj{A,B,C} are all running together as one parallel "block". In the current behavior, I'm led to think that only buildProj{B,C} are designated to run in parallel.
