### ISSUE TITLE
Serial/Parallel Sub Op Run Designation Via Block

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#526]
specify serial/parallel via block

``` YAML
run:
  subOps:
    - serial:
      - url: serial-1_1
      - url: serial-1_2
    - parallel:
      - url: parallel-1
      - serial:
        - url: serial-2_1
        - url: serial-2_2
      - url: parallel-2
    - serial:
      - url: serial-3_1
```
