### ISSUE TITLE
Allow path expansion w/in sub op call inputs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#542]
Example:
```yaml
inputs:
  srcDir:
    dir: {}
outputs:
  dstFile:
    file: {}
run:
  op: 
    pkg: { ref: xyz }
    inputs: { xyzInputFile: $(srcDir)/myFile.txt  }
```
