### ISSUE TITLE
Allow string/number literals as sub op call inputs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#543]
```yaml
inputs:
  notAmbiguous:
    string: {}
run:
  op: 
    pkg: { ref: xyz }
    inputs: 
      xyzString: string value
      xyzNumber: 2
      # w/out $(), would be ambiguous if ref or string literal w/ val `notAmbiguous`
      yxz: $(notAmbiguous) 
```
