### ISSUE TITLE
Allow interpolation in container dir/file binds

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#544]
```yaml
container:
  files:
    $(rootPath)/some-dir/$(descendantPath)/$(fileName).$(fileExtension)
  dirs:
    $(rootPath)/some-dir/$(descendantPath)
```
