### ISSUE TITLE
Allow Numbers & Implicit Binding On Container Ports

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#569]
```yaml
container:
    ports:
        # numbers
        80: 90
        # implicit binding
        80-84:
```
