### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#570]
### Reference
- [loop in javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration)

##### Option 1
 thoughts: 
   - extends existing definition format
   - not as declarative as 2 because you must define your own loop variables
```YAML
run:
  serial:
    - op:
        ref: github.com/opspec-pkgs/opspec.op.list-deps#1.0.0
        inputs:
          opDotYml: $(op/op.yml)
        outputs:
          deps:
    - forEach:
        items: $(deps)
        (dep):
          serial:
            - op:
                ref: github.com/opspec-pkgs/opspec.op.update-dep#1.0.0
                inputs:
                  opDotYml: $(op/op.yml)
                  dep:
```

##### Option 2
 thoughts: 
   - extends existing definition format

```YAML
run:
  serial:
    - name: listDeps
      op: 
        ref: github.com/opspec-pkgs/opspec.op.list-deps#1.0.0
        inputs:
          opDotYml: $(op/op.yml)
    - name: depUpdateLoop
      forEach: $(listDeps.deps)
      serial:
        - name: updateDep
          op: 
            ref: github.com/opspec-pkgs/opspec.op.update-dep#1.0.0
            inputs:
              opDotYml: $(op/op.yml)
              # $(depUpdateLoop.value) is "auto" property set to value of current loop iteration
              dep: $(depUpdateLoop.value)
```

##### Option 3
> leverages [Declarative concurrency](https://github.com/opspec-io/spec/issues/178)

 thoughts:
   - call hierarchy not human readable
```YAML
run:
  listDeps:
    op:
      ref: github.com/opspec-pkgs/opspec.op.list-deps#1.0.0
      inputs:
        opDotYml: $(op/op.yml)
  updateDep:
    startOn:
      any:
        $(listDeps.SUCCEEDED)
    forEach:
      items: $(listDeps.outputs.deps)
      (dep):
        op: 
          ref: github.com/opspec-pkgs/opspec.op.update-dep#1.0.0
          inputs:
            opDotYml: $(op/op.yml)
            dep:
```
