### ISSUE TITLE
Interpolate Param Defaults

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#572]
Param defaults were rolled before interpolation support. Now that we have interpolation, we should also support it in input defaults.

This would also entail support for absolute path defaults for files/dirs. This will be a breaking change but shouldn't be too bad as it's not used too frequently. Currently absolute paths in file/dir param defaults are interpreted w/ respect to the op dir. This would change to the callers root dir, as w/ interpolation u can reference the root op dir unambiguously via $(/)
 
Lastly, we should support defaults for sockets as well which would be interpreted w/ respect to the caller

```yaml
inputs:
  defaultedArray:
    array:
      default: $(/myArray.json)
  defaultedBoolean:
    boolean:
      default: $(/boolean.txt)
  defaultedDir:
    dir:
      default: $(/)
  defaultedFile:
    file:
      default: $(/op.yml)
  defaultedNumber:
    number:
      default: $(/number.txt)
  defaultedObject:
    object:
      default: $(/myObj.json)
  defaultedSocket:
    socket:
      default: /var/run/docker.sock
```
