### ISSUE TITLE
Couldn't show in list in stable

### ISSUE THREAD

**Issue by RoynKo** [opctl/opctl#573]
```yaml
name: loop-test
description: Loop testing
inputs:
  carBrands:
    array:
      default: [Ford, Toyota, Honda]
run:
  loop:
    index: index
    until: 
      - eq: [index, 10]
  container: 
    image: { ref : 'alpine: 3.8' }
    cmd: 
      - sh
      - - ce
      - echo hi ${name} at index ${index}
```
By using `opctl ls` in stable, this one not shown in list. But works in alpha.
