### ISSUE TITLE
Conditional Running

### ISSUE THREAD

**Issue by psamaan** [opctl/opctl#576]
## Use Case
As a user I want to specify a condition to be checked before my op runs so that I don't need to wrap scripts in `if` statements.

## Proposal
* Specifying a property in `op` whose value is a logical expression that's evaluated at runtime and if true, the op runs.
* The expression may contain any input in scope, and support logical operators ( AND, OR, NOT). It must evaluate to `true` or `false`
* `false` is the boolean value of `false`, empty strings, and null variables

## Example
In the below example, build will only run if it's needed. i.e. if the current commit doesn't already have a matching docker image tag. In all cases, deploy will run.
```
name: ship
description: builds docker image and deploys it to a specific environment. target tag should be current commit.
inputs:
  srcDir:
    dir:
      description: project directory containing source code
      default: ./
  dockerSocket:
    socket:
      description: path to socket of Docker daemon
run:
  serial:
    - op:
        ref: get-commit
        inputs:
          srcDir:
        outputs:
          commit:
    - op:
        ref: get-latest-image-tag
        inputs:
          dockerSocket:
        outputs:
          latestTag:
    - op:
        ref: build
        condition: latestTag != commit
        inputs:
          srcDir:
          dockerSocket:
    - op:
        ref: deploy
```

Note: This may still be required even if #178 is accepted.
