### ISSUE TITLE
Exists predicate

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#580]
### Use Case
*As* a user of opspec
*I* want an exists predicate
*So* I can make ops with behavior conditioned on the existence of values

## Example
```yaml
if:
  - exists: $(notInScope) # false
  - exists: $(inScope) # true
  - exists: $(inScope.doesNotExist) # false
```
