### ISSUE TITLE
NotExists predicate

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#581]
### Use Case
*As* a user of opspec
*I* want a  notExists predicate
*So* I can make ops with behavior conditioned on the non existence of values

## Example
```yaml
if:
  - notExists: $(notInScope) # true
  - notExists: $(inScope) # false
  - notExists: $(inScope.doesNotExist) # true
```
