### ISSUE TITLE
value of true results in binding error

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#582]
repro:

```
name: elasticsearch
run:
  container:
    image: { ref: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.2' }
    envVars:
      discovery.type: single-node
      TAKE_FILE_OWNERSHIP: true
```

expected: no error
actual:  `Msg='unable to bind env var to 'TAKE_FILE_OWNERSHIP' via implicit ref; 'TAKE_FILE_OWNERSHIP' not in scope'`
