### ISSUE TITLE
Allow dynamically setting env vars of a container

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#584]
## User Story
*As* the maintainer of an op
*I want* to dynamically set the env vars of a container 
*In order to* reduce maintenance when env vars are sourced from an object

## Example

before:
```
      - container:
          image: { ref: 'alpine' }
          envVars:
             MY_ENV_VAR1: $(envVars.MY_ENV_VAR1)
             MY_ENV_VAR2: $(envVars.MY_ENV_VAR2)
             MY_ENV_VAR3: $(envVars.MY_ENV_VAR3)
```

after:
```
      - container:
          image: { ref: 'alpine' }
          envVars: $(envVars)
