### ISSUE TITLE
Interpreting Implicit Binding Of Loop Variable Errors

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#586]
example of call that will fail

```yaml
    - loop:
        for:
          each: $(appNames)
          value: repoName
      op:
        ref: _cloneCheckoutRepo
        inputs:
          githubAccessToken:
          githubUsername:
          srcDir:
          repoName: $(repoName)
```
