### ISSUE TITLE
Support numbers & objects as opcall inputs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#600]
Support the following when composing ops
```yaml
op:
  pkg: { ref: xyz }
  inputs: 
    numberInput: 2
    objectInput: { field1: xyz, field2: 2 }
```
