### ISSUE TITLE
Support passing pkg dir/file as sub op arg

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#607]
```yaml
run:
  op:
    pkg: { ref: xyz }
    inputs: { file: /fileFromPkg, dir: /dirFromPkg }
```
