### ISSUE TITLE
Add `assign` call

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#617]
## User Story
`As` an author of an op
`I want` to assign variables without starting a container
`In order` to have clearer semantics and better performance

## Example
```yaml

    - container:
        image: { ref: 'opspecpkgs/aws.secretmanager.get-secret-value:1.0.0' }
        cmd: [/cmd.sh]
        envVars:
          AWS_ACCESS_KEY_ID: $(accessKeyId)
          AWS_DEFAULT_REGION: $(region)
          AWS_SECRET_ACCESS_KEY: $(secretAccessKey)
          AWS_SESSION_TOKEN: $(sessionToken)
          secretName:
        files:
          /cmd.sh:
          /secretObject: $(secretObject)
    - if:
        - exists: $(secretObject.SecretString)
      assign:
        secretValue: $(secretObject.SecretString)
    - else:
        - exists: $(secretObject.SecretBinary)
      assign:
        secretValue: $(secretObject.SecretBinary)
```
