### ISSUE TITLE
Default not supported for socket input type

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#630]
From the [documentation](https://github.com/opctl/opctl/blob/3448d572b362e6c408b217df61fbb6f579f2cc0f/docs/getting-started.md#L85):

> `default` property: You can define a `default` property for each input, containing a value to assign if no other input method was invoked (cli args or args file)

However, this doesn't work for sockets:

```yml
description: test for socket default
name: test
inputs:
  aSocket:
    socket:
      default: /foo
run:
  container:
    image: { ref: 'ubuntu' }
    cmd: ['echo', 'foo']
```

```
-
  Error(s):
    - inputs.aSocket.socket: Additional property default is not allowed
-
```
