### ISSUE TITLE
opctl silently hangs when mounting from home directory

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#633]
Minimal op:
```yml
description: |
  minimal repro
name: test
inputs:
  HOME:
    string:
      description: Home directory
run:
  container:
    image: { ref: 'alpine' }
    cmd: ['/bin/sh', '-c', 'cat /testfile']
    files:
      /testfile: $(HOME/testfile)
```

Output:
```
▻ opctl run test
OpStarted Id='45a236ba562c4b2eb760d4bcf7a7e9a4' OpRef='/path/to/test' Timestamp='2019-09-30T08:43:33Z'
```

This hangs indefinitely. When I try to kill it with ctrl-c, I get:
```
^CGracefully stopping... (signal Control-C again to force)
request resulted in a recoverable error & will be retried; error was: Post http://localhost:42224/api/ops/kills: EOF
request resulted in a recoverable error & will be retried; error was: Post http://localhost:42224/api/ops/kills: dial tcp [::1]:42224: connect: connection refused
request resulted in a recoverable error & will be retried; error was: Post http://localhost:42224/api/ops/kills: dial tcp [::1]:42224: connect: connection refused
OpEnded Id='45a236ba562c4b2eb760d4bcf7a7e9a4' OpRef='/path/to/test' Outcome='KILLED' Timestamp='2019-09-30T08:45:07Z'
```

The same thing happens when mounting directories.

Sorta related to https://github.com/opctl/opctl/issues/630#issuecomment-536463891.
