### ISSUE TITLE
Referencing Non Directories As Directories Hangs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#637]
## Repro
Run this op
```
name: kaboom
inputs:
  kaboom:
    string:
      default: hello
run:
  container:
    image: { ref: alpine }
    cmd: [echo, $(kaboom/notafile)]
```

## Expected
error gracefully and tell you it can't interpret $(HOME/testfile) as a file because HOME is not a directory

## Actual
node hangs; ctrl+c from cli times out.
