### ISSUE TITLE
Add support for "readiness" when sequencing ops

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#640]
I'd like to be able to have a first-class way to delay an operation starting before another is "ready".

The specific use case is running tests in a codebase that requires a ready database and redis instance. I want to say "wait for redis and database to be ready, then run another op".

There are a couple ways I can think of to "know" when a service is ready:
- Watch for some certain pattern to be output on stdout. (preferred for me)
- Use an http health check.

I'd definitely like some sort of non-polling mechanism (an event trigger, instead of a try catch and repeat), since I think it'll be more understandable and will avoid needing to trade off between the perf overhead of frequent checks and the time overhead of a delay between checks.

FYI @drewandersen
TAGS: wait, ready, delay

**Comment by chrisdostert** [comment]
@apexskier You can typically do this today via wrapping your think w/ dependency in a serial block as in:

```yaml
- parallel:
  - # run your dep like db
  - serial:
    - # wait until your dep is in the state u want
    - # run your thing w/ dependency
```

Side note, triggers are going to be supported at some point and will light up a number of use cases. The idea is a trigger will cause re-execution of a subgraph of an operation similar to how react components work. I need to write it up; it's just in my head and historical conversations at the moment.

**Comment by apexskier** [comment]
How does this part work? That's kind of what I'm asking about.
> wait until your dep is in the state u want

**Comment by chrisdostert** [comment]
example from @luisgarciaalanis 
```yaml
name: db/rebuild
description: clears and rebuilds the db
inputs:
  appDir:
    dir:
      description: Application root direactory
      default: .
  rentisoDBPassword:
    string:
      description: password to connect to the database
      isSecret: true
      default: password
  rentisoDBSchema:
    string:
      description: name of the Rentiso schema db
      default: rentisodb
  rentisoDBUsername:
    string:
      description: name of the db user
      default: rentiso
  rentisoDBPort:
    string:
      description: name of the Rentiso db port
run:
  serial:
    - op:
        ref: ../db/clean
        inputs: { appDir }
    - op:
        ref: ../db/init
        inputs: { appDir }
    - parallel:
      - op:
          ref: github.com/opspec-pkgs/mysql.db.run#1.0.1
          inputs: 
            dbDataRootDir: $(appDir/database/mysql-data)
            dbPassword: $(rentisoDBPassword)
            dbSchema: $(rentisoDBSchema)
            dbUsername: $(rentisoDBUsername)
            dbUseNativePassword: true
      - serial:
        - op:
            ref: github.com/opspec-pkgs/mysql.db.waitready#1.0.1
            inputs:
              dbHost: mysqldb
              dbPassword: $(rentisoDBPassword)
              dbSchema: $(rentisoDBSchema)
              dbUsername: $(rentisoDBUsername)
        - op:
            ref: ../db/migrate
            inputs:
              appDir:
              rentisoDBUsername:
              rentisoDBPassword:
              rentisoDBSchema:
              rentisoDBPort:
        - op:
            ref: ../db/seed
            inputs:
              appDir:
              rentisoDBUsername:
              rentisoDBPassword:
              rentisoDBSchema:
              rentisoDBPort:
```
