### ISSUE TITLE
Op file output with `.` in name doesn't work

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#641]
Given these three ops in the same opspec directory:

```yml
# .opspec/foo/op.yml
description: testing
name: foo
outputs:
  test.file:
    file:
      description: test output
run:
  container:
    image: { ref: 'alpine' }
    cmd: ['/bin/sh', '-c', "cat /file > /output"]
    files:
      /file: |
        hello world (foo)
      /output: $(test.file)
```
```yml
# .opspec/bar/op.yml
description: testing
name: bar
outputs:
  testfile:
    file:
      description: test output
run:
  container:
    image: { ref: 'alpine' }
    cmd: ['/bin/sh', '-c', "cat /file > /output"]
    files:
      /file: |
        hello world (bar)
      /output: $(testfile)
```
```yml
# .opspec/test/op.yml
description: testing
name: foo
run:
  serial:
    - op:
        ref: foo
        outputs:
          test.file:
    - container:
        image: { ref: 'alpine' }
        cmd: [cat, /file]
        files:
          /file: $(test.file)
    - op:
        ref: bar
        outputs:
          testfile:
    - container:
        image: { ref: 'alpine' }
        cmd: [cat, /file]
        files:
          /file: $(testfile)
```

The output of the `foo` op is empty, but `bar` works, so I see "hello world (bar)" printed but not "hello world (foo)".
