### ISSUE TITLE
Named calls and needs

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#643]
## User Story
**As** an op designer
**I want** the ability to name calls and allow other calls to declare they need them.
**In order to** end the execution of those calls when they're no longer needed

## Example

```yaml
name: integration test
run:
  parallel:
    - systemUnderTest:
        container:
          image: { ref: systemUnderTest }
    - needs: [$(systemUnderTest)]
      container:
        image: { ref: testHarness }
```
