### ISSUE TITLE
Allow Interpolating Container `workDir`

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#648]
## User Story
*As* an op designer
*I want* to be able to use interpolation in a containers `workDir` declaration
*In order* to avoid imperatively changing my workDir inside the container when my binary requires a variable workDir

## Example

```yaml
name: workdirInterpolation
inputs:
  subfolder:
    string:
      default: default
run:
  container:
    image: { ref: my-image }
    cmd: [do-stuff-in-project/default]
    workDir: project/$(subfolder)
```
