### ISSUE TITLE
Path Breakout Shouldn't Be Possible

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#650]
### User Story
*As* an user of an op
*I* should have assurance the file tree I pass an op is all that can be accessed by the op
*In order* to avoid it having access to more than I intend

### Example
An op designer shouldn't be able to do $(appDir/..)
```yaml
inputs:
  appDir:
    dir:
      default: .
run:
  serial:
    - op:
        ref: github.com/opspec-pkgs/git.repo.clean#1.1.0
        inputs: { srcDir: $(appDir/..) }
```
