### ISSUE TITLE
Spread Syntax

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#651]
### User Story
*As* an op designer
*I want* to merge objects/arrays/dirs natively
*In order* to not need to call a merge op for this purpose which takes more lines of code and is slower due to having to start a container. 

### Examples
Objects such as `container.envVars`
```yaml
envVars: 
  # value of spread key `...` is an array in order to support spreading multiple values w/ precedence
  ...: [$(vars)]
  # all other entries take precedence over entries sourced from spread key
  AWS_REGION: $(aws.region)
  AWS_ACCESS_KEY_ID: $(assumedRole.Credentials.AccessKeyId)
  AWS_SECRET_ACCESS_KEY: $(assumedRole.Credentials.SecretAccessKey)
  AWS_SESSION_TOKEN: $(assumedRole.Credentials.SessionToken)
```

Dirs such as `container.dirs`
```yaml
dirs:
  /:
    ...: [$(files)]
    src: $(appDir)
```
