### ISSUE TITLE
Can't define an input without properties

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#654]
I have an op that's an internal utility. It has inputs, but they're always provided by the main op you use so I don't want them to have duplicated details (default/description).

Example opspec:
```yml
name: internal
inputs:
  foo:
    boolean:
```

I'll get the error:
```
  Error(s):
    - inputs.foo.boolean: Invalid type. Expected: object, given: null
```

I'd expect this to work, since all properties of the expected object are optional.

**Comment by chrisdostert** [comment]
Hey, you can do what you want but just need to make the boolean attribute non null (nothing on right side of colon is null in yaml). This should be you want

```yaml
name: internal
inputs:
  foo:
    boolean: {}
```

**Comment by chrisdostert** [comment]
closing; feel free to re-open if not solved.

**Comment by apexskier** [comment]
I'd like to re open until it's fixed, should be a simple matter of adding a default of empty object instead of null. I'm not able to open issues in this repo.

**Comment by chrisdostert** [comment]
Ah sorry, didn't think of that. 

Having a value of null for an input parameter is the equivalent of a language syntax error. 
We have no way to know what type the parameter is without it being non null.

**Comment by apexskier** [comment]
If you look at my example, I'm not looking to pass untyped parameters, just to not pass arguments to the type specification.
```yml
name: internal
inputs:
  foo:
    boolean:
```
not
```yml
name: internal
inputs:
  foo:
```

---
It's definitely possible to default to something other than null - it's supported when passing parameters to sub-ops:
This is supported:
```yml
- op:
    ref: internal
    inputs:
      foo:
```
I'm not required to do this:
```yml
- op:
    ref: internal
    inputs:
      foo: $(foo)
```

**Comment by chrisdostert** [comment]
```yaml
name: internal
inputs:
  foo:
    boolean:
```
after parsing by yaml parser is identical to
```yaml
name: internal
inputs:
  foo:
    string: null
    dir: null
    file: null
    number: null
    boolean: null
    socket: null
```
so what type is the parameter? This is why it's a syntax error.
