### ISSUE TITLE
Container Name 

### ISSUE THREAD

**Issue by lilaja** [opctl/opctl#655]
Is there a way to name a container? 
currently when I run a container op, the container gets a random UUID string as a name.

I thought that container.name option will assign the name, but it is not working 
(i guess it is rather a network alias - btw i would rename it :) )

Op example: 
```yaml
name: dockerName
run:
  container:
    image: { ref: 'alpine:3.9' }
    cmd: ["tail", "-f",  "/dev/null"]
    name: jhonny-bravo
```

current `docker ps` output
```
CONTAINER ID       NAMES
fa6a548c41e4       8837e530cb0f4bde82d7383acddf54f7
```

expected `docker ps` 
```
CONTAINER ID       NAMES
fa6a548c41e4       jhonny-bravo
```

_____
opctl version: 0.1.25
