### ISSUE TITLE
Files/Dirs as objects

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#666]
## User Story
*As* an op designer
*I want* to reference attributes of files/directories natively
*In order* to avoid needing to use an op to do so

## Example
```yaml
inputs:
  appDir:
    dir:
      default: .
  image:
    dir:
      default: image
run:
  op:
    ref: github.com/opspec-pkgs/fs.cp-dir#2.0.1
    inputs:
      src: $(image)
      userId: $(appDir.userId)
      groupId: $(appDir.groupId)
      dstPath: /image
      dst: $(appDir)
```
