### ISSUE TITLE
Templated object initializer doesn't hydrate file references correctly

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#674]
## Repro
1. run this op:
```yaml
name: doh
inputs:
  opYml:
    file:
      default: /op.yml
run:
  container:
    image: { ref: alpine }
    cmd:
      - sh
      - -ce
      - echo -n "${nested}"; echo;
    envVars:
      nested:
        opYml:
```

## Expected
```shell
{"opYml":"name: doh\ninputs:\n  opYml:\n    file:\n      default: /op.yml\nrun:\n  container:\n    image: { ref: alpine }\n    cmd:\n      - sh\n      - -ce\n      - echo -n \"${nested}\"; echo;\n    envVars:\n      nested:\n        opYml:"}
```

## Actual
```shell
{"opYml":"/Users/source/todelete/op.yml"}
```
