### ISSUE TITLE
Image call type

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#689]
## User Story
*As* an op author
*I want* to natively define images via opspec
*In order* to avoid relying on non-native image building/caching solutions which are less visible and make my overall experience disconnected & more complicated.

```yaml
image:
  layers:
    - from:
         ref: php:7.1-apache
    - env:
        APACHE_DOCUMENT_ROOT: /src/app
    - copy:
        /src/app: $(src/appDir)
    - run:
        - sh
        - -ce
        - pecl install xdebug-2.6.0 && docker-php-ext-enable xdebug
```
