### ISSUE TITLE
Container net socket binding

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#690]
## User Story
`As` an op designer
`I want` to explicitly expose sockets from my op and bind them to a container therein
`In order` to avoid port conflicts & breaking encapsulation

## Example
```yaml
name: dev
inputs:
  appSocket:
    socket:
      default: myapp.local:7886
  debugSocket:
    socket:
      default: myapp.local:40000
run:
  container:
    image: { ref: 'myapp' }
    sockets:
      0.0.0.0:7886: $(appSocket)
      0.0.0.0:4000: $(debugSocket)
```

## Notes
depending on capabilities/implementation; we might need a network level proxy to do this; see below for ideas:
- https://github.com/norouter/norouter
- https://github.com/sumup-oss/gocat
- https://github.com/staaldraad/tcpprox for tcp proxy
- https://godoc.org/golang.org/x/net/proxy
- https://github.com/orbstack/orbstack/issues/33
