### ISSUE TITLE
Make opctl ls error if invalid ops are encountered

### ISSUE THREAD

**Issue by zimnyjakub** [opctl/opctl#708]
## 🐛 Bug Report
When you put in an error inside of an op and it does not validate via `opctl run` it also does not show up in `opctl ls`

## To Reproduce

Given an example op.yml:

```
name: build
inputs:
  appDir:
    dir:
      default: .
run:
  serial:
    - container:
        dirs:
          /app: $(appDir)
        image: { ref: node:12.13-alpine }
        workDir: /app
        cmd:
          - yarn
          - install
    - container:
        dirs:
          /app: $(appDir)
        image: { ref: node:12.13-alpine }
        workDir: /app
        envVars: # <- error is here
        cmd:
          - yarn
          - install
```

when running `opctl ls`

then it shows empty list

## Expected behavior

I expect `opctl ls` to still show the op even if it contains errors. Optionally i can be warned that specification has error in yml file.

I only found out that the op has an error when tried to run it 

## Actual Behavior

`opctl ls` should show all ops, regardless if yml file has an error or not
