### ISSUE TITLE
Allow referencing environment variables in input defaults

### ISSUE THREAD

**Issue by ddenisen** [opctl/opctl#717]
## 🚀 Feature

It would be nice to be able to reference shell environment variables inside the `default:` value for op inputs so that we can derive default values from them.

## Motivation

Sometimes the best default value is actually a function of the user's environment. A user account-global cache dir is a specific example:
```
name: dev
description: Dev op to build and run a Java service
inputs:
  cacheDir:
    description: Gradle cache directory
    default: $(HOME)/.gradle
```

Without this features, I have to manually define `cacheDir` in my shell profile prior to running the op:
```
export cacheDir=$HOME/.gradle
```

## Pitch

See above

**Comment by chrisdostert** [comment]
Thanks for filing! We want to do something to support this use case. 

An issue that comes with referencing things not in scope in defaults (like env vars of the caller) is you lose composability. For example, what if you called it from another op instead of from a CLI; there's no "environment" so it couldn't use the default.

The proposal I personally think might be most promising so far is from Jared, which was to allow referencing other inputs from defaults (see below for example). The only real downside to this is you could have cycles (input defaults referencing inputs with defaults that reference the original input). 

```
name: dev
description: Dev op to build and run a Java service
inputs:
  HOME:
    dir: {}
  cacheDir:
    string:
      description: Gradle cache directory
      default: $(HOME/.gradle)
```
