### ISSUE TITLE
Make input/output binding when calling ops consistent

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#721]
## 💥 Proposal
When calling an op. inputs/outputs are currently bound via:
```
inputs:
  definedInput: $(myInputVar)
outputs:
  $(myOutputVar): definedOutput
```

it's a common gotcha for newcomers that input/output binding syntax is reversed

The proposal is to make them match so above would become:
```
inputs:
  definedInput: $(myInputVar)
outputs:
  definedOutput: $(myOutputVar)
```
