### ISSUE TITLE
image.ref with multi-variable templated string not working since v0.1.28

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#722]
## 🐛 Bug Report
image.ref with templated strings containing multiple variable references regressed in 0.1.28

## To Reproduce

1) using opctl 0.1.28 or greater, run an op with a multi variable templated string as its image.ref e.g.
```yaml
container:
        image:
          ref: $(imageRegistry)/$(imageName):$(imageVersion)
```

## Expected behavior

op runs same as in 0.1.27

## Actual Behavior

receive the following error:
```shell
 interpreting image src; error was: unable to interpret $(imageRegistry)/$(imageName):$(imageVersion) to dir; error was unable to interpret '$(imageVersion' as reference; expected ')''
```
