### ISSUE TITLE
Nonexistent sub dirs bound to containers aren't sync'd

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#725]
## 🐛 Bug Report
If I pass an input directory to an op and bind a non existent subdirectory to a container; the sub directory is not properly sync'd back to my client.

## To Reproduce

1. Run
```yaml
name: test
inputs:
  dummyDir:
    default: .
run:
  container:
    image: { ref: alpine }
    dirs:
      # notExists will not show up in bound dummyDir; only in the container
      /dummyDir: $(dummyDir/notExists)
```

## Expected behavior
`ls` and you should see `notExists`

## Actual Behavior
don't see `notExists`
