### ISSUE TITLE
Duplicate container names and indeterminate behavior

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#726]
## 🐛 Bug Report

Given this simple opspec

```yml
name: foo
run:
    parallel:
        - container:
            name: bar
            image: {ref: alpine}
            cmd: [sleep, 100000]
        - container:
            name: bar
            image: {ref: alpine}
            cmd: [sleep, 100000]
```

What will happen if another op calls `http://bar`?

More seriously, if I reference an external op with a named container, how do I know if a container name I use conflicts with a container name it uses?
