### ISSUE TITLE
Default pkg source credentials

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#744]
## 🚀 Feature

Add support for configurable or "default" pkg source credentials, to avoid needing to re-enter on the command line each time and make it easier to automate ops in a non-interactive environment.

This could be implemented in a number of ways. My proposal is to storing some config yml file in `$XDG_CONFIG_HOME/opctl/credentials.yml` with a way to match package sources with credentials.

The structure could be something like:

```yml
credentials:
- source: github.com/Remitly
  username: $(github.username) # environment variable / object reference
  password: $(github.accessToken)
- source: github.com
  username: myusername # plain text
  password: $(GITHUB_PASSWORD) # environment variable
```

This attempts to math opctl's opspec format. It uses opctl's [object property referencing](https://opctl.io/docs/opspec/reference/types/object#property-referencing) syntax and its ability to [read environment variables](https://opctl.io/docs/zero-to-hero/inputs-outputs).

It would use the credential source to match the pkg source's prefix and use the first credential found (e.g. `opctl run -a apiKey=$LOKALISE_TOKEN github.com/Remitly/parakeet#v1.0.0/parakeet-ops/update-all-locales` would match the first credential, not the second).
