### ISSUE TITLE
Opspec validation for bad `output` names

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#798]
## 🚀 Feature

Opctl should fail when an invalid `output` name is used.

## Motivation

Given this op:

```yml
description: Run the app
name: run
run:
  serial:
    - op:
        ref: github.com/opspec-pkgs/object.merge#1.0.0
        inputs:
          default:
            a: 1
            b: 2
            c: 3
          override:
            b: asdf
        outputs:
          vars:
    - container:
        image: { ref: 'alpine' }
        envVars: $(vars)
        cmd: ['env']
```

I get this error message:
```
unable to interpret '$(vars)' as envVars; error was unable to interpret $(vars) to object; error was unable to interpret 'vars' as reference; 'vars' not in scope
```

## Pitch

The error message currently points to my subsequent usage in the container as the error (where I use "envVars"). This is misleading, as it's actually the `run.serial[0].op.outputs` that contains an error. This ideally would be a validation check that would show me the opspec that's incorrect.
