### ISSUE TITLE
container.envVars string double interpreted

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#849]
## 🐛 Bug Report

container.envVars string is interpreted twice

## To Reproduce

1. run this op:
    ```yaml
    name: double
    inputs:
      vars:
        object:
          default:
            key: $(notInScope)
    run:
      container:
        cmd: [sh, -ce, env]
        image:
          ref: alpine
        envVars: $(vars)
    ```

## Expected behavior
runs successfully and logs 
```sh
HOSTNAME=2cc3cd3bfb0d
SHLVL=1
HOME=/root
key=$(notInScope)
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
```

## Actual Behavior
fails with
```sh
Error='unable to interpret $(notInScope) as value of env var 'key'; error was unable to interpret $(notInScope) to string; error was unable to interpret 'notInScope' as reference; 'notInScope' not in scope' Id='99681d8d3b064bba9a59963569a9dc78' OpRef='/Users/source/repos/github.com/dummy' Timestamp='2020-12-23T00:01:42Z'
```
