### ISSUE TITLE
Output variable is not bound

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#892]
## 🐛 Bug Report

In a larger op I'm writing I'm trying to conditionally add an item to a list of environment variables. However, I'm running into an issue where the original object containing my variables can't be created.

## To Reproduce

Here's a minimal reproduction of the broken opspec

```yml
name: test

run:
  serial:
    - op:
        ref: github.com/opspec-pkgs/object.merge#1.0.0
        inputs:
          default:
            DOMAIN: dev
          override:
            TEST: foo
        outputs:
          envVars:
    - container:
        image: { ref: "alpine" }
        envVars: $(envVars)
        cmd:
          - env
```

## Expected behavior

I'd expect the `envVars` variable to be available.

Cli output:
```
OpStarted Id='a7eaa84e6b334ec9bf4349ef5896f58d' OpRef='/Users/cameronlittle/Developer/mothra/.opspec/debug-codegen' Timestamp='2021-03-18T14:59:07Z'

ContainerStarted Id='8455382b628e4303bce8a149182bd768' OpRef='/Users/cameronlittle/Developer/mothra/.opspec/debug-codegen' ImageRef='docker.io/library/alpine' Timestamp='2021-03-18T14:59:07Z'

latest: Pulling from library/alpine
Digest: sha256:a75afd8b57e7f34e4dad8d65e2c7ba2e1975c795ce1ee22fa34f8cf46f96a3be
Status: Image is up to date for alpine:latest
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=fff6c342e33a
TERM=xterm
HOME=/root
DOMAIN=dev
TEST=foo
ContainerExited Id='8455382b628e4303bce8a149182bd768' ImageRef='docker.io/library/alpine' Outcome='SUCCEEDED' Timestamp='2021-03-18T14:59:10Z'

OpEnded Id='a7eaa84e6b334ec9bf4349ef5896f58d' OpRef='/Users/cameronlittle/Developer/mothra/.opspec/debug-codegen' Outcome='SUCCEEDED' Timestamp='2021-03-18T14:59:10Z'
```

## Actual Behavior

```
OpStarted Id='6edceee92a1143939d4cdc858a990364' OpRef='/Users/cameronlittle/Developer/mothra/.opspec/debug-codegen' Timestamp='2021-03-18T14:59:49Z'

OpStarted Id='aa88af6fa41040b1a0fdea30d7dff173' OpRef='/Users/cameronlittle/Library/Application Support/opctl/ops/github.com/opspec-pkgs/object.merge#1.0.0' Timestamp='2021-03-18T14:59:49Z'

ContainerStarted Id='b119b36c269541c2a0cea1e768903291' OpRef='/Users/cameronlittle/Library/Application Support/opctl/ops/github.com/opspec-pkgs/object.merge#1.0.0' ImageRef='docker.io/library/node:11.13-alpine' Timestamp='2021-03-18T14:59:49Z'

11.13-alpine: Pulling from library/node
Digest: sha256:72aef1f7a5088ee3b162b1f9eafb48e8b76a9fc9df70169cb6cce75cff7fefce
Status: Image is up to date for node:11.13-alpine
ContainerExited Id='b119b36c269541c2a0cea1e768903291' ImageRef='docker.io/library/node:11.13-alpine' Outcome='SUCCEEDED' Timestamp='2021-03-18T14:59:54Z'

OpEnded Id='aa88af6fa41040b1a0fdea30d7dff173' OpRef='/Users/cameronlittle/Library/Application Support/opctl/ops/github.com/opspec-pkgs/object.merge#1.0.0' Outcome='SUCCEEDED' Timestamp='2021-03-18T14:59:54Z'

Error='unable to interpret '$(envVars)' as envVars; error was unable to interpret $(envVars) to object; error was unable to interpret 'envVars' as reference; 'envVars' not in scope' Id='d3ecfe8ab2034bc0b9611f58e7c4e433' OpRef='/Users/cameronlittle/Developer/mothra/.opspec/debug-codegen' Timestamp='2021-03-18T14:59:54Z'

Error='unable to interpret '$(envVars)' as envVars; error was unable to interpret $(envVars) to object; error was unable to interpret 'envVars' as reference; 'envVars' not in scope' Id='ab681ed6de324118b634b460cd7b48cd' OpRef='/Users/cameronlittle/Developer/mothra/.opspec/debug-codegen' Timestamp='2021-03-18T14:59:54Z'

OpEnded Id='6edceee92a1143939d4cdc858a990364' OpRef='/Users/cameronlittle/Developer/mothra/.opspec/debug-codegen' Outcome='FAILED' Error='unable to interpret '$(envVars)' as envVars; error was unable to interpret $(envVars) to object; error was unable to interpret 'envVars' as reference; 'envVars' not in scope' Timestamp='2021-03-18T14:59:54Z'

```

**Comment by chrisdostert** [comment]
This is what you want; the sole output from that particular op is called `result` so you need to either use that as is or bind to an in scope variable

```
name: test

run:
  serial:
    - op:
        ref: github.com/opspec-pkgs/object.merge#1.0.0
        inputs:
          default:
            DOMAIN: dev
          override:
            TEST: foo
        outputs:
          result: $(envVars)
    - container:
        image: { ref: "alpine" }
        envVars: $(envVars)
        cmd:
          - env
   ```

**Comment by chrisdostert** [comment]
and you already filed an improvement ticket to enforce you can't do this ; ) https://github.com/opctl/opctl/issues/798

**Comment by apexskier** [comment]
@chrisdostert Do you know why this doesn't work?

```
name: test

run:
  serial:
    - op:
        ref: github.com/opspec-pkgs/object.merge#1.0.0
        inputs:
          default:
            DOMAIN: dev
          override:
            TEST: foo
        outputs:
          results: $(vars)
    - container:
        image: { ref: "alpine" }
        envVars: $(vars)
        cmd:
          - env
```
