### ISSUE TITLE
Make description a property of a variable; not a property of it's data type

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#898]
## 💥 Proposal
When defining input/output variables, currently `description` is a property of the data type. This is not logical; it should be a property of the variable (i.e. one level higher); not its type .

Also, defining it as a property of the variable will allow input/output variable specs to be consistent with call specs when we support adding descriptions.

### existing
```yaml
inputs:
  domain:
    description: the deploy domain
    string: {}
 ```
### proposed
```yaml
inputs:
  domain:
    string:
      description: the deploy domain
```
