### ISSUE TITLE
Make inputs/outputs an array

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#899]
## 💥 Proposal
Currently inputs/outputs are maps where the key is variable name and the value is the spec (type specific). This is inconsistent from how calls are defined in the call graph. In the call graph, each call can have a `name` property which serves as the variable name by which it can be referenced, and the spec is at the same level (type specific). 

> note1: we would obviously need to support both for some period of time because all existing specs treat them as a map.
> note2: see also https://github.com/opctl/opctl/issues/900 for further making input/output variable specs consistent w/ call specs.

### existing (assuming https://github.com/opctl/opctl/issues/898)
```yaml
inputs:
  domain:
    description: txt to echo
    string: {}
run:
  name: echo
  container:
    image:
      ref: alpine
    cmd: [echo, $(txt)]
```

### proposed (assuming https://github.com/opctl/opctl/issues/898)
```yaml
inputs:
  - name: domain
    description: txt to echo
    string: {}
run:
  name: echo
  container:
    image:
      ref: alpine
    cmd: [echo, $(txt)]
```
