### ISSUE TITLE
Allow defining description on call graph nodes

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#900]
## 🚀 Feature
Currently you can define a `name` for calls but it would be nice to also support `description`.

### existing (assuming https://github.com/opctl/opctl/issues/898)
```yaml
inputs:
  domain:
    description: txt to echo
    string: {}
run:
  name: echo
  container:
    image:
      ref: alpine
    cmd: [echo, $(txt)]
```

### proposed (assuming https://github.com/opctl/opctl/issues/898)
```yaml
inputs:
  - name: domain
    description: txt to echo
    string: {}
run:
  name: echo
  description: This container will take the input $(txt) and log it via the echo comman
  container:
    image:
      ref: alpine
    cmd: [echo, $(txt)]
```
