### ISSUE TITLE
Array/Dir/File/Number/Object/String call types 

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#901]
## 🚀 Feature
Currently we have no way to define variables in the call graph. They must either be defined as inputs/outputs or implicitly via binding a variable to a container file/dir/socket. The former is limiting because it means we have to create a container simply to define a variable. The latter is limiting because it's a foot gun; there's no protection if you intend a variable to be provided but you forget, it will happily do what you don't intend and define a new variable.

### Example
```
name: echoer
inputs:
  name:
    string:
      description: name of caller
run:
  serial:
    - name: greeting
      description: The greeting to echo
      string:
        default: Hello $(name)!
    - name: echo
      description: This container echoes a greeting to the caller!
      container:
        image:
          ref: alpine
        cmd: [echo, $(greeting)]
```
