### ISSUE TITLE
Serial loop using until doesn't seem to work

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#909]
## 🐛 Bug Report

An example op using serial loop and until doesn't work.

## To Reproduce

```yaml
name: test
description: |
  This is an example op.yml file that counts down using a serial loop
inputs:
  counter:
    number:
      default: 2
run:
  serialLoop:
    until:
      - eq: [$(counter), 0]
    run:
      container:
        image: { ref: alpine }
        cmd:
          - sh
          - -c
          - |
            echo $(counter)
            echo "\$(($(counter)-1))" > /file
        files:
          /file: $(counter)
```

## Expected behavior

Emits 2, 1, 0, then exits.

## Actual Behavior

Emits 2, 1, 0, -1, -2, ... and doesn't exit.

If I switch `eq` with `ne`, the op exits immediately, so the predicate is being evaluated. Adding `if: [eq: [$(counter), 2]` behaves as expected (the op runs), so eq is broken for numbers.
