### ISSUE TITLE
Add boolean predicates

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#911]
## 🚀 Feature

Predicates are useful, but I currently find them overly verbose for most use cases. Because opctl supports boolean typed values, I think there could be a much more intuitive and simple way to to use them by adding a predicate that supports boolean values.

Currently, I commonly use these predicates, which I find somewhat unintuitive/confusing without thinking carefully.

```yml
if:
  - eq: [$(myValue), true]
  - eq: [$(myValue), false]
  - ne: [$(myValue), true]
```

### Pitch A

The basic idea would be to interpret a non-object predicate as a boolean value and have the predicate return true if the value either evaluates or is coerced to `true`.

```yml
if:
  - $(myBooleanVariable)
  - $(myStringVariable)
```

```yml
if: [$(variable)]
```

Taken further, there could be a shorthand format used instead of a list of predicates (in `if` and `until`). If a non-array value or variable reference is found, it will be coerced to a boolean and evaluated:

```yml
if: $(myVariable)
if: true
```

### Pitch B

Pitch A could be confusing, since the schema would accept either a well defined structure, or an arbitrary variable, and coercion would only be applied in certain cases. An alternative could be supporting explicit boolean predicates, which avoids coercion ambiguity (the right hand side is always treated as a value):

```yml
if:
  - true: $(variable)
  - false: $(variable)
```

(alternative naming: `is`/`not`)
