### ISSUE TITLE
Variable driven port binding

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#976]
## 💥 Proposal
The current port binding syntax provides a way to expose an opctl container port to the host it's running on. 

A limitation of the current approach is that it breaks encapsulation; only one process at a time can bind a given host port so if a process is already running on the host on a port bound by a container in an op, it won't be able to start.

A major intention behind opctl is to provide a virtualized runtime; node processes should not effect the behavior of running an op.

The proposed enhancement to the existing syntax is to allow binding [socket typed](https://opctl.io/docs/reference/opspec/types/socket) variables to container ports (similar to how a container dir or file can be bound to variables). 

This would allow the caller of the op to choose where/if to mount the socket.

Example:
```yaml
name: improvedPorts
inputs:
  apiSocket:
    socket:
      default: localhost:80 # or could be name-to-add-to-hostfile:80 or /path/to/mount/as/unix/socket
run:
  container:
    image:
      ref: myApi
    sockets:
      80: $(apiSocket)
```
