### ISSUE TITLE
Improve predicate syntax, add new comparators

### ISSUE THREAD

**Issue by tallen94** [opctl/opctl#984]
## 🚀 Feature
I would like to make some improvements to the predicate syntax, using if statements.

* We should add an `else` block
* Add support for ordering comparisons, `gt`,` lt`, `gte`, `lte`

Something else that seems weird is the predicates have to be listed under one of the main control flow blocks: `serial`, `parallelLoop`, etc.

I think there should be a `predicate:` block so that it is clear only one of the statements will be evaluated. This would make it more nested, but I think gain clarity

## Motivation

The motivation for this is to make syntax more clear and cover more use cases in boolean logic.

## Pitch

Here is an example trying to implement a basic `if number > 1: else:`:
In order to accomplish this we have to set a minimum constraint on the number, and check `if number == 1: if number !== 1`

```
inputs:
  arraySize:
    number:
      constraints:
        minimum: 1
run:
  serial:
      - if:
          - eq: [$(arraySize), 1]
        op:
          ref: ../aws-cmd
          inputs:
            HOME:
      - if:
          - ne: [$(arraySize), 1]
        op:
          ref: ../aws-cmd
          inputs:
              HOME:
              size: $(arraySize)
```

would become:
```
inputs:
  arraySize:
    number:
run:
  predicate:
      - if:
          - lte: [$(arraySize), 1]
        op:
          ref: ../aws-cmd
          inputs:
            HOME:
      - else:
         op:
           ref: ../aws-cmd
           inputs:
              HOME:
              size: $(arraySize)
```

The latter seems more explicit and clear what this evaluates to.

**Comment by chrisdostert** [comment]
I've been chewing on this. What about:
```yaml
inputs:
  arraySize:
    number:
run:
inputs:
  arraySize:
    number:
run:
  if:
    condition:
      - lte: [$(arraySize), 1]
    then:
      op:
        ref: ../aws-cmd
        inputs:
          HOME:
    else:          
      op:
        ref: ../aws-cmd
        inputs:
          HOME:
          size: $(arraySize)
```

Something kinda cool is you can nest other `if`'s as needed within the then or else.
